static int     addt(int    nums[], int length);
static double  addt(double nums[], int length);
static float   addt(float  nums[], int length);
static int     subt(int    nums[], int length);
static double  subt(double nums[], int length);
static float   subt(float  nums[], int length);
static int     mult(int    nums[], int length);
static double  mult(double nums[], int length);
static float   mult(float  nums[], int length);
static int     divt(int    nums[], int length);
static double  divt(double nums[], int length);
static float   divt(float  nums[], int length);
static int     remt(int    nums[], int length);
static int     powt(int    nums[], int length);
static double  powt(double nums[], int length);
static float   powt(float  nums[], int length);
static double  sqrArea(double side);
static double  rctnglArea(double base, double height);
static double  trnglArea(double base, double height);
static double  rhombArea(double largestDiagonal, double smallestDiagonal);
static double  rhomboidArea(double base, double height);
static double  trapArea(double largestBase, double smallestBase, double height);
static double  regPolygonArea(double perimeter, double apothema);
static double  circArea(double radio);
static double  circLenght(double diameter);
static int*    fib(int n);
static double  power(double base, int exp);
static double  hypotenuse(double cat1, double cat2);
static int     fact(int n);
static double  abslt(double n);
static double  exp(int x);
static double  max(double num1, double num2);
static double  min(double num1, double num2);
static int     hcd(int num1, int num2);
static int     mcm(int num1, int num2);
static int     sqroot(double num, double apx, int n);
static int     sqroot(int n);
static bool    isPI(double n);
static bool    isEULER(double n);
static bool    isGAMMA(double n);
static bool    isTAU(double n);
// Here we defined Maths' functions